export * from "./catalog/types.js";
export { compileCatalog, gateReport } from "./catalog/compile.js";
export type { CompileInput, GateReport } from "./catalog/compile.js";
export * from "./ontology/types.js";
export { Lexicon, normalizeText } from "./ontology/lexicon.js";
export { FURNITURE_PACK } from "./ontology/furniture-pack.js";
export { applyOverrides } from "./ontology/overrides.js";
export type { PackOverrides } from "./ontology/overrides.js";
export { proposeColor, proposeLineMaterial, swatchFamily } from "./ontology/furniture-naming.js";
export * from "./engine/types.js";
export { QueryEngine } from "./engine/engine.js";
export * from "./turn/state.js";
export * from "./turn/planner.js";
export { Reducer } from "./turn/reducer.js";
export type { EngineAction } from "./turn/reducer.js";
export { Renderer } from "./turn/render.js";
export type { UiCard } from "./turn/render.js";
export { Verifier } from "./turn/verifier.js";
export type { Segment, Verdict } from "./turn/verifier.js";
export { TurnGateway } from "./turn/gateway.js";
export type { LlmJsonClient, TurnRequest, TurnResult, TurnTrace } from "./turn/gateway.js";
export { templateAnswer } from "./turn/templates.js";
